config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users,     only: [:new, :create, :show]
  resources :sessions,  only: [:new, :create, :destroy]
  resources :events,    only: [:new, :create, :show, :destroy, :index]
  resources :favorites, only: [:new, :create, :show, :destroy, :index]

  match '/home',              to: 'sessions#new',                 via: 'get'
  match '/search',            to: 'events#search',                via: 'get' 
  match '/favorites',         to: 'favorites#index',              via: 'get'
  match '/signup',            to: 'users#new',                    via: 'get'
  match '/signin',            to: 'sessions#new',                 via: 'get'
  match '/signout',           to: 'sessions#destroy',             via: 'delete'
  match '/results',           to: 'events#index',                 via: 'get'

 

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :event 
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def search
  end

  def show # Weird
    @user_favorites = current_user.events
  end

  def index
    @current_user_events = current_user.events
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/index.html.erb
<div class="jumbotron div_bg_light">
  <% @current_user_events.each do |event| %>

  <div style="float: right">
  <%= link_to "delete", event, method: :delete, data: { confirm: "Are you sure?" } %>
  </div>

  <div class="move_left">
    <p><%= event.title %></p>
    <p><%= event.date %></p>
    <p><%= event.location %></p>
    <p><%= event.description %></p>
  </div>
  <% end %>
</div>

app/views/favorites/show.html.erb
<% provide(:title, "Favorites") %>
<h1>My Favorites</h1>

<div>
<% unless @user_favorites.nil? %>
  <% @user_favorites.each do |event| %>
  <div>
    <div style="float: right">
   <!--  <%# link_to "Add to favorites", events_path(event: { title: event["title"], venue_id: event["id"],  location: event["region_name"], date: event["start_time"], description: event["description"] } ), method: :post %> -->
    </div>
    <p><%= event.title %></p>
    <p><%= event.location %></p>
    <p><%= event.description %></p>
  </div>
  <% end %>
<% end %>
</div>