config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :users,     only: [:new, :create, :show]
  resources :sessions,  only: [:new, :create, :destroy]
  resources :events,    only: [:new, :create, :show, :destroy, :index]
  resources :favorites, only: [:new, :create, :show, :destroy, :index]

  match '/home',              to: 'sessions#new',                 via: 'get'
  match '/search',            to: 'events#search',                via: 'get' 
  match '/favorites',         to: 'favorites#index',              via: 'get'
  match '/signup',            to: 'users#new',                    via: 'get'
  match '/signin',            to: 'sessions#new',                 via: 'get'
  match '/signout',           to: 'sessions#destroy',             via: 'delete'
  match '/results',           to: 'events#index',                 via: 'get'

 

end

app/views/layouts/_navigation.html.erb
<nav class="navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/favorites">My Favorites</a>
      <a class="navbar-brand" href="/search">New Fuel Search</a>     
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
        <!--       <li><%# link_to "Profile", current_user %></li> -->
              <li><%# link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Sign In", signin_path %></li>
        <% end %>
      </ul>
      <p class="navbar-text navbar-right">Fuel Up!</p>
 <!--      <form class="navbar-form navbar-right" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<head>
  <title>Life!Fuel | <%= yield (:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="new_background">
  <%= render 'layouts/navigation' %>
  <div class="container">


  <%= flash[:notice] %>

  <%= yield %>
  </div>

</body>
</html>